name: tasks
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

 #Icons
  cupertino_icons: ^1.0.8
  iconsax_flutter: ^1.0.0

#State Management
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  go_router: ^15.1.2 


  #Utility Packages
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.6
  animated_bottom_navigation_bar: ^1.4.0
  modal_bottom_sheet: ^3.0.0
  universal_stepper: ^1.0.0+1
  flex_color_picker: ^3.7.1
  cloud_firestore: ^5.6.8
  skeletonizer: ^1.4.3
  equatable: ^2.0.7
  flutter_local_notifications: ^19.2.1
  auto_size_text_field: ^2.2.4
  fluttertoast: ^8.2.12
  flutter_steps: ^1.0.5
  infinite_scroll_pagination: ^5.1.0
  flutter_animate: ^4.5.2

    
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/
    - assets/images/content/

  # An image file can appear as "assets/images/imagename" in
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800


scripts:
  splash:
    - dart pub run flutter_native_splash:create  --path=splash.yaml
    - dart pub run flutter_native_splash:remove --path=splash.yaml