name: Build Bleu Agent Dev APKs

on: [push]
jobs:              
    build:
      runs-on: ubuntu-latest   
      steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_ID }}
          message: |
            Commit : 
            ${{ github.event.commits[0].message }}
            
            Commit by:${{ github.actor }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

        # - uses: actions/checkout@v3
        # - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
        
        # - name: install dependencies
        #   run: flutter pub get

        # - name: Build application
        #   run: flutter build apk -t lib/main.dart --split-per-abi
        
        # - name: Send apk
        #   run: |
        #     curl -F document=@build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk "https://api.telegram.org/bot${{ secrets.BOT_ID }}/sendDocument?chat_id=${{ secrets.CHAT_ID }}&caption=Bleu%20Tasks%20ARMv7a"
        #     curl -F document=@build/app/outputs/flutter-apk/app-arm64-v8a-release.apk "https://api.telegram.org/bot${{ secrets.BOT_ID }}/sendDocument?chat_id=${{ secrets.CHAT_ID }}&caption=Bleu%20Tasks%20ARMv8a"
